HummingBird version1.0
googleinterns/cros-hummingbird pull request #2
Opened 2021-08-04 08:32 UTC by paying4529

Complete basic function

2021-08-04 08:40 UTC, p9n commented on extension.json
> +      	"spec": {
fix the indent

2021-08-04 08:41 UTC, p9n commented on extension.json
> +  "name": "HummingBird",
I guess we need a more descriptive name if we want to publish.

Should be okay right now.

2021-08-04 11:40 UTC, p9n commented on generate_report.py
> +__main__ = ["SVGfile", "OutputReportFile"]
what's __main__ for?

2021-08-04 11:40 UTC, p9n commented on generate_report.py
> +    points += f"{i//rate*5},{(data_max - int(data[i]*50))*2 + 40} "
I guess the string concat is slow when data is very large. You can try to output to the html file directly

2021-08-04 11:40 UTC, p9n commented on generate_report.py
> +    field:  the SPEC field of this SVF plot
SVF -> SVG

2021-08-04 11:41 UTC, p9n commented on generate_report.py
> +  report_path = temp_path+f"/{time_now.strftime('%Y-%m-%d-%H%M%S')}report.html"
use `os.path.join(temp_path, f"...")`

2021-08-04 11:43 UTC, p9n commented on hummingbird.py
> +#raise Exception(os.path.dirname(__file__))
remove this line

2021-08-04 11:46 UTC, p9n commented on hummingbird.py
> +        f.close()
no need to close since you are using `with`.

2021-08-04 11:56 UTC, p9n commented on hummingbird.py
> +  def measure(self):
Split this into small functions, i.e. write a function for each step

2021-08-04 11:58 UTC, p9n commented on hummingbird.py
> +      os.system(f"open {report_path}")
Use [subprocess.run(["open", report_path])](https://docs.python.org/3/library/subprocess.html#subprocess.run)

2021-08-04 12:01 UTC, p9n commented on hummingbird.py
> +    uni_addr = list(set(uni_addr))
no need because duplicated addresses in `uni_addr` is already removed in line 907

2021-08-04 12:03 UTC, p9n requested changes
Just putting some general comments here, still need some time to review the measure() function.

- Variable naming:
    - Use upper case for global constants like `TEMP_PATH`
    - The "f" in `SVGfile` should be upper case
- https://google.github.io/styleguide/pyguide.html#36-whitespace
    -  Surround binary operators with a single space on either side
- Google now recommends 4 space indent. I know this is really hard to change at this time, so this is optional :p
- You can put the parameter type in function signature, for example `def SVGfile(data: np.array, data_max: float, data_min: float, ...)`
- (bonus item) try to upload a generated html to [w3c validator](https://validator.w3.org/) to check if it has any syntax error

2021-08-05 07:40 UTC, paying4529 commented
- indent, parameter type, html format, variables, uni_addr, subprocess fixed
- change type decision flow
- save output report to HummingBird local downloaded directory

2021-08-06 01:27 UTC, paying4529 commented
- split measure into small functions

2021-08-06 03:55 UTC, paying4529 commented
- directly write report rather than concat string

2021-08-06 04:11 UTC, p9n commented on generate_report.py
> +    rect_width = max(rect_width//rate * 5, 7)
whitespace around `//`, also at line 73 and 82

2021-08-06 04:12 UTC, p9n reviewed
Looks really good now, thanks.
One more thing: remove the .pyc files.

Also there's some future tasks, no need to do in this PR:
- Add __pycache__ to .gitignore to prevent uploading unwanted files again
- Add unittests

2021-08-06 05:43 UTC, paying4529 commented
- delete pyc file
- add whitespace

2021-08-09 04:58 UTC, p9n approved these changes

2021-08-09 04:58 UTC, p9n commented on README.md
> +A report html file would be generated at /var/tmp/report.html
this line needs update

2021-08-09 04:59 UTC, merged